#!/bin/sh

set -e

rm -Rf fsbuild/_build
rm -f hatari hatari.exe tos.img

echo "Downloading hatari-2.3.1.tar.bz2..."
URL=https://download.tuxfamily.org/hatari/2.3.1/hatari-2.3.1.tar.bz2
SHA256=44a2f62ca995e38d9e0874806956f0b9c3cc84ea89e0169a63849b63cd3b64bd
python3 fsbuild/download.py "$URL" sha256:$SHA256

echo "Extracting hatari-2.3.1.tar.bz2..."
mkdir -p fsbuild/_build
cd fsbuild/_build
rm -Rf hatari-2.3.1 hatari-src
tar xf ../_sources/hatari-2.3.1.tar.bz2
mv hatari-2.3.1 hatari-src

echo "Applying patches..."
cd hatari-src
# Don't want to link to (nor include) readline library
sed -i.tmp "s/find_package(Readline)//g" CMakeLists.txt
# Fix main function in source generators on Windows
patch -p1 < ../../../mingw.patch
# Skip building tests and tools to avoid patching for mingw
sed -i.tmp "s/add_subdirectory(tests)//g" CMakeLists.txt
sed -i.tmp "s/add_subdirectory(tools)//g" CMakeLists.txt

echo "Bootstrap done"
